### ISSUE TITLE
SSL

### ISSUE THREAD

**Issue by anton-dutov** [locka99/opcua#1]
Why openssl dependency instead of native-tls?

**Comment by locka99** [comment]
OPC UA for Rust is using OpenSSL for functions to read / write X509 certs, read / write private keys, asymmetric Rsa encrypt / decrypt with different padding, asymmetric verify / sign, symmetric AES decrypt / verify, hmac, sha1, sha256 and a few other things.

What it doesn't need is to open a TLS connection. so native-tls is no use to me. Native-tls seems designed to just open a stream with crypto and read/write from it.

I would be happy to flip to a general purpose Rust crypto library if it provided everything I need but I'm not aware of one just yet. 

Crypto is still work in progress. I have the asymmetric handshake working, pki layout, plus 95% of the constituent parts. I'm just working through some signing issues in the symmetric crypto. No timeline on this but once it's working I'll probably bump the release to 0.2.
