### ISSUE TITLE
[Help Required] How to get tag values related to server status?

### ISSUE THREAD

**Issue by jigar88** [locka99/opcua#127]
is there a way to get server status in the tag for monitoring, like weather server is started or running or broken? Or I need to use server status node defined in the server state to get the server status ? In python there is a function like server.is_running() , is there anything equivalent available ?

also I tried to use server info in the Ignition client but most of the nodes are null and not showing data.
![image](https://user-images.githubusercontent.com/75369224/125513867-49a698e8-89e9-4aae-a50b-34ac753b5cf5.png)

**Comment by schroeder-** [comment]
If you are on the server side:
Get [server_state](https://docs.rs/opcua-server/0.8.0/opcua_server/server/struct.Server.html#method.server_state) and then use [is_running](https://docs.rs/opcua-server/0.8.0/opcua_server/state/struct.ServerState.html#method.is_running)

**Comment by locka99** [comment]
I think if you're writing a server it is better to push state into OPC UA rather than try fetch state from it.

**Comment by jigar88** [comment]
How do you push state ?
