### ISSUE TITLE
client history_read not usable

### ISSUE THREAD

**Issue by schroeder-** [locka99/opcua#130]
I try to use the session history_read methode in the current master. The first parameter history_read_details, needs the enum HistoryReadDetails (opcua_client/session.rs). But the enum has a nameing conflict with the struct HistoryReadDetails in (opcua_types/services/history_read_details.rs). And only the struct HistoryReadDetails is accessible. I don't know the best solution maybe rename the enum in HistoryRead?

**Comment by locka99** [comment]
I've renamed it to HistoryReadAction. Also HistoryUpdateAction. I'm sure you could disambiguate by pulling in the opcua_types crate and a direct use but this would be easier.
