### ISSUE TITLE
Does this library support HistoryRead 

### ISSUE THREAD

**Issue by liuweiXX** [locka99/opcua#158]
I tried toUaExpert to read a historical data using UaExpert, but fails
![屏幕截图 2022-01-18 205619](https://user-images.githubusercontent.com/77447777/149942171-fecba967-0308-4719-bc12-c79800873b96.png)

**Comment by schroeder-** [comment]
Out of the box there is no support for HistoryReadRaw. But you can hook your own history backend into the server see:
[historical.rs](https://github.com/locka99/opcua/blob/64844b9e6de7c2dbd8aacfa48a4c2d57aa3e96ac/samples/demo-server/src/historical.rs)
There is just a barebone and returns not supported. But you can write your own logic to provide history values.

**Comment by locka99** [comment]
Yes it's something you need to implement. The server could conceivably offer some kind of simple history backend but at the moment leaves it up to the implementation to do something with the call.

**Comment by locka99** [comment]
Closing since the answer is yes
