### ISSUE TITLE
Please create tag for 0.9.1 release

### ISSUE THREAD

**Issue by laumann** [locka99/opcua#208]
Was a little surprised when docs.rs informed me that the latest version is 0.9.1: https://docs.rs/opcua-client/latest/opcua_client/. I see the branch, but afaict there's no tag for it.

**Comment by locka99** [comment]
There is a 0.9.1 branch for it, not a tag. There is also a version 0.10 where all the crates have been consolidated as just opcua instead of opcua-server, opcua-client etc.

**Comment by laumann** [comment]
The reason I ask is that it's nice to have them show up on the [tags page](https://github.com/locka99/opcua/tags) that I frequently use for various projects.

**Comment by locka99** [comment]
I've pushed a tag for it there.

**Comment by laumann** [comment]
Nice! Thank you!
