### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by shrmrf** [locka99/opcua#28]
The licensing is ~~unclear~~ (clear, but missing the `LICENSE.md` file) on this repo. Might be a good idea to put a `LICENSE.md` file at the root of the repo.

---
BTW, I don't know how I missed this, but thanks for the rust OPC UA implementation. Is there a Gitter or Slack channel where you guys discuss future stuff or dev topics?

**Comment by locka99** [comment]
Thanks, I've merged it in

**Comment by locka99** [comment]
I don't have a discussion channel, but I respond to requests (within time/reason!)
