### ISSUE TITLE
opcua client run on tokio runtime

### ISSUE THREAD

**Issue by cppcoffee** [locka99/opcua#286]
I use the `opcua-client` crate. I see that `Client` and `Session` are sync, Any suggestions on how to use them under tokio runtime?

Are `opcua-client` crate any plans to support async?

https://github.com/locka99/opcua/blob/master/lib/src/client/client.rs#L192

**Comment by abdelhaksam** [comment]
Hi,
You can use tokio's `task::spawn_blocking` and use sync code inside.

**Comment by cppcoffee** [comment]
Okay, I'll use `task::spawn_blocking` for this.
