### ISSUE TITLE
tokio task is not stopped on session disconnect

### ISSUE THREAD

**Issue by denizs** [locka99/opcua#32]
In our setup, we are experiencing unpredictable behaviour of the OPC server where sessions are dropped silently on server side, forcing us to close and reconnect as soon as a read out fails. 
~Our implementation involves dropping the current session and starting from scratch.~
We also tried `session.disconnect()` and `session.close_secure_channel()`

If this happens a couple of times, we are running in to "Too many open files", because the `connection_task` run by Tokio is not terminated after a session is dropped.

**Edit:**
The problem remains if you call `session.disconnect()`

**Comment by locka99** [comment]
This is most likely the same as #16

**Comment by denizs** [comment]
Do you have any clue on how to fix this? Looking at the code from a high level perspective, it seems like properly cleaning up the `connection_task` should do the trick, or am I mistaking

**Comment by locka99** [comment]
I'll have to go back and see if I can debug it again. Part of the reason all the tasks have debugging around their success / failure states is from previous attempts to figure out which task wasn't exiting when it was supposed to.

If your server is trying to periodically register with an OPC discovery server and this is the cause, then one workaround is to disable that behaviour. 

e.g. i.e. set this via a builder

builder.discovery_server_url(None)

or this in a server.conf

discovery_server_url: ~

Then the server won't periodically call the discovery server, which it does an OPC UA client and therefore there is no call to create a connection_task.

**Comment by denizs** [comment]
The problem is that we don't have any control over the server. We are using the client only.

**Comment by denizs** [comment]
I investigated this issue a little bit more. If you call disconnect, the `WriteState` isn't dropped. This is easy to achieve by calling `close_secure_channel` on the session. However, this doesn't seem to close the open file descriptor. I then had a look into the `WriteHalf<TcpStream>` and found that apparently, the `shutdown` method [doesn't do anything](https://github.com/tokio-rs/tokio/issues/852).

**Comment by locka99** [comment]
Thanks for investigating this. I'll see if I can spare some time to look I to this. I know I've wrapped some futures in a completion pact struct (https://github.com/locka99/opcua/blob/master/server/src/completion_pact.rs) to put additional logic in and perhaps the same can be done here. Obviously if I can't stop a task when it is an unrecoverable state then that would be bad....

**Comment by denizs** [comment]
It seems like this is indeed related to #16. When letting the process continue, I see debug output of tokio_reactor::registration scheduling reads. Seems like the read half stays open

**Comment by locka99** [comment]
I think I've fixed this on the trunk. There are a number of scenarios where some of the tasks in the client / server side wouldn't necessarily close properly and I've tried to make it more robust. The reader task now sends an explicit quit to the writer when the socket breaks or finishes with an error.
