### ISSUE TITLE
Client browse ViewDescription timestamp

### ISSUE THREAD

**Issue by TheGr8Nik** [locka99/opcua#47]
With OPC Factory Server (Schneider's OFS) browsing a NodeId different from root folder returns a `BadViewIdUnknown` error.
Looking the session browse method source code I saw that `ViewDescription::timestamp` is set to `DateTime::now()` [session.rs](https://docs.rs/opcua-client/0.7.0/src/opcua_client/session.rs.html#1264).
Changing that row to `DateTime::epoch()` will fix the issue and the browse request is executed correctly.

**Comment by locka99** [comment]
Thanks for the report, I've updated the code. Reading the spec for Browse it says the time should be "null" which I shall treat to be 0, or the epoch in other words. Seems some servers are more strict than others about it.
