### ISSUE TITLE
CTT

### ISSUE THREAD

**Issue by pulzzedavid** [locka99/opcua#52]
Is there a plan to work with CTT? We are starting to put the library through CTT, and finding some issues. So, wondering what the ideal strategy is for fixing issues related to CTT.

**Comment by locka99** [comment]
I don't have access to the CTT. If the OPC UA foundation were to offer me the tools and option to certify I would be able to fix a bunch of stuff I'm sure

**Comment by pulzzedavid** [comment]
Please contact me on david at interactor dot com for CTT discussion
