### ISSUE TITLE
Session Name configuration

### ISSUE THREAD

**Issue by pulzzedavid** [locka99/opcua#94]
Looks like session name is hard coded. 

`let session_name = UAString::from("Rust OPCUA Client");`

Would be good to have it configurable. If configurable session name is currently supported, some pointer would be much appreciated.

**Comment by locka99** [comment]
I've made it configurable through a config file and through the builder.

**Comment by pulzzedavid** [comment]
Thanks, much appreciate a quick turn around. Will test it out.
